name: Build
on: 
  workflow_dispatch:
 
jobs:
 node-1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest]
    timeout-minutes: 5
 
    steps:
      - uses: actions/checkout@v4
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
              curl ipinfo.io
              timeout --preserve-status 10s sleep 30s
              echo OK
        shell: bash
        
 node-2:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest, ubuntu-latest]
    timeout-minutes: 5
 
    steps:
      - uses: actions/checkout@v4
      - run: mkdir runner
      - name: Setup App
        working-directory: ./runner
        run: |
              curl ipinfo.io
              timeout --preserve-status 10s sleep 30s
              echo OK
        shell: bash
